### ISSUE TITLE
Feedback for intern.plus

### ISSUE THREAD

**Issue by helpwhatname** [alexieyizhe/intern.plus#117] opened 2019-11-25 22:59 UTC
Crashed every time you clicked anything

**Comment by alexieyizhe** [comment] 2019-11-27 15:52
@helpwhatname oh no

**Comment by helpwhatname** [comment] 2019-11-27 15:54
Laptop (acer)
Internet edge (latest)

**Comment by helpwhatname** [comment] 2019-11-27 15:55
works on chrome its just that i used edge at the time of opening it for some reason

**Comment by alexieyizhe** [comment] 2019-11-27 15:58
Could you open up the edge dev console (<kbd>F12</kbd> I think) and see if there's any errors there?

I'll have to get a hold of a Windows laptop to reproduce because it's working for me on MacOS Edge Dev

**Comment by helpwhatname** [comment] 2019-11-27 16:00
![image](https://user-images.githubusercontent.com/58194152/69739025-fbc8be80-1104-11ea-9d2e-0fa7cb0a5b11.png)

TypeError: Object doesnt support property or method "flatMap"

**Comment by alexieyizhe** [comment] 2019-11-27 23:39
I just released a new version that should've addressed this issue - could you try going on Edge again and seeing if the problem is resolved?

**Comment by alexieyizhe** [comment] 2019-12-03 18:22
Tested on Edge Windows 10 with no crashes - closing this!

**Closed by alexieyizhe** 2019-12-03 18:22 UTC
Labels: status: response needed
